// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytlsddjlxjgxsepszpmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0bHNkZGpseGpneHNlcHN6cG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTE0NjYsImV4cCI6MjA3MzQ4NzQ2Nn0.DZNDKTXKHzWWmPjWenWu8mI4CeZk2ScveiUQhoo0hw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});